name: Python

on: [push, pull_request]

env:
    FORCE_COLOR: 2

jobs:
    run:
        name: Ubuntu
        runs-on: ubuntu-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v2

            - name: Run tests
              run: python test_geohexa.py
